name = "PhyloPlots"
uuid = "c0d5b6db-e3fc-52bc-a87d-1d050989ed3b"
license = "MIT"
version = "0.2.2"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
DataFrames = "≥ 0.13.0"
Gadfly = "≥ 1.0.0"
PhyloNetworks = "≥ 0.9.0"
RCall = "≥ 0.11.0"
julia = "≥ 0.7.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
